[package]
name = "rustdom-x-compact-vm"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[features]
differential-audit = []

[dependencies]
blake2b_simd = "1.0.4"
randomx-softfp = { path = "../softfp" }
rustdom-x = { path = "../rustdom-x", features = ["unchecked-superscalar"] }
