[workspace]
members = [
    "argon2",
    "randomx-sp1-argon2-audit",
    "audit",
    "randomx-sp1",
    "executor",
    "profile-probes",
    "program",
    "randomx-core",
    "softfp",
    "softfp-guest",
    "softfp-runner",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.91"
version = "0.1.0"

[profile.release]
lto = "thin"
