[package]
name = "randomx-compact-vm-cfround-program"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[features]
nearest-only-audit = ["rustdom-x-compact-vm/nearest-only-audit"]

[dependencies]
rustdom-x = { path = "../rustdom-x", features = ["unchecked-superscalar"] }
rustdom-x-compact-vm = { path = "../compact" }
sp1-zkvm = "=6.3.1"
