[package]
name = "randomx-sp1"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "SP1-optimized, runtime-key RandomX hashing"
readme = "README.md"
license = "GPL-3.0-only"
publish.workspace = true

[features]
audit-internals = []
differential-audit = ["audit-internals"]

[dependencies]
blake2b_simd.workspace = true
randomx-softfp.workspace = true
randomx-sp1-core = { workspace = true, features = ["unchecked-superscalar"] }
