[package]
name = "randomx-sp1-executor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "SP1 execution, profiling, and PGU estimation tool for randomx-sp1"
publish.workspace = true

[features]
profiling = ["sp1-core-executor-runner/profiling"]

[dependencies]
anyhow.workspace = true
hex.workspace = true
sp1-core-executor.workspace = true
sp1-core-executor-runner.workspace = true
