[package]
name = "randomx-sp1-profile-probes"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[features]
default = ["cache-only"]
cache-only = []
no-memory-hash = []

[dependencies]
randomx-sp1-core = { path = "../randomx-core", features = ["unchecked-superscalar"] }
randomx-sp1 = { path = "../randomx-sp1" }
sp1-zkvm = "=6.3.1"

[dev-dependencies]
blake2b_simd = "=1.0.4"
hex = "=0.4.3"
