[package]
name = "randomx-sp1-core"
version.workspace = true
edition = "2024"
rust-version.workspace = true
description = "Internal RandomX cache, dataset, and VM primitives for randomx-sp1"
readme = "README.md"
license = "GPL-3.0-only"
publish.workspace = true

[lib]
name = "randomx_sp1_core"

[features]
default = ["unchecked-superscalar"]
compact-superscalar = ["precompute-reciprocal"]
precompute-reciprocal = []
unchecked-superscalar = ["compact-superscalar"]

[dependencies]
blake2b_simd.workspace = true
randomx-sp1-argon2.workspace = true
strum.workspace = true
