[package]
name = "randomx-sp1-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
description = "Internal RandomX cache, dataset, and VM primitives for randomx-sp1"
readme = "README.md"
license = "GPL-3.0-only"
publish = false

[lib]
name = "randomx_sp1_core"

[features]
default = ["unchecked-superscalar"]
compact-superscalar = ["precompute-reciprocal"]
precompute-reciprocal = []
unchecked-superscalar = ["compact-superscalar"]

[dependencies]
blake2b_simd = "=1.0.4"
libc = "=0.2.189"
log = "=0.4.33"
randomx-sp1-argon2 = { path = "../argon2" }
strum = { version = "=0.24.1", features = ["derive"] }
